/* English Quest — reliable word translation for every lesson */
(function(){
  const phraseDictionary={"choose a school item.":"Выбери школьный предмет."};
  const dictionary={what:"что",is:"есть / является",it:"это",a:"артикль",an:"артикль перед гласным звуком",blue:"синий / голубой",colour:"цвет",color:"цвет",circle:"круг",ten:"десять",five:"пять",fifteen:"пятнадцать",twenty:"двадцать",choose:"выбери",correct:"правильный",sentence:"предложение",my:"мой / моя / моё",name:"имя",lily:"Лили",school:"школа",item:"предмет",pencil:"карандаш",apple:"яблоко",apples:"яблоки",dog:"собака",eraser:"ластик",ruler:"линейка",pen:"ручка",book:"книга",books:"книги",bag:"сумка",schoolbag:"школьная сумка",number:"число",thirteen:"тринадцать",three:"три",thirty:"тридцать",one:"один",two:"два",family:"семья",moments:"моменты",i:"я",have:"иметь / у меня есть",got:"есть / получил",sister:"сестра",sisters:"сёстры",brother:"брат",you:"ты / вы",he:"он",she:"она",mummy:"мама",daddy:"папа",grandma:"бабушка",grandpa:"дедушка",plural:"множественное число",this:"это / этот",that:"то / тот",these:"эти",those:"те",who:"кто",things:"вещи",like:"нравиться / любить",likes:"нравится",milk:"молоко",pizza:"пицца",drink:"напиток",some:"немного / некоторое количество",any:"какой-нибудь / сколько-нибудь",juice:"сок",toys:"игрушки",come:"приходи / приходить",in:"в / внутри",play:"играть",possession:"принадлежность",box:"коробка",boxes:"коробки",teddy:"плюшевый",bear:"медведь",bears:"медведи",room:"комната",bedroom:"спальня",chair:"стул",robot:"робот",ball:"мяч",animals:"животные",furry:"пушистый",can:"мочь / уметь",can’t:"не может","can't":"не может",run:"бегать",fly:"летать",fish:"рыба",walk:"ходить",ear:"ухо",cow:"корова",frog:"лягушка",kangaroo:"кенгуру",mouse:"мышь",paws:"лапы",paw:"лапа",home:"дом",sweet:"милый / сладкий",cat:"кошка",on:"на",where:"где","where’s":"где находится","where's":"где находится",kitchen:"кухня",table:"стол",lamp:"лампа",bathroom:"ванная",garden:"сад",day:"день",off:"выходной",playing:"играет",park:"парк",doing:"делаешь / делаете",drawing:"рисую",riding:"катается / едет",bike:"велосипед",watching:"смотрим",tv:"телевизор",football:"футбол",they:"они",they’re:"они / они сейчас","they're":"они / они сейчас",we’re:"мы / мы сейчас","we're":"мы / мы сейчас",running:"бегает",yesterday:"вчера",get:"получать / вставать",up:"вверх",at:"в / в указанное время",seven:"семь",time:"время",o’clock:"часов","o'clock":"часов",daily:"ежедневный",brush:"чистить",teeth:"зубы",morning:"утро",now:"сейчас",know:"знать",go:"идти",to:"частица перед глаголом",bed:"кровать / спать",open:"открой",your:"твой / ваш",please:"пожалуйста",sit:"сядь",down:"вниз",read:"читать",say:"скажи / сказать",schoolbag:"школьная сумка",teacher:"учитель",classroom:"класс",subject:"предмет",penсil:"карандаш",mum:"мама",dad:"папа"};

  function styles(){if(document.getElementById("translationTooltipStyles"))return;const s=document.createElement("style");s.id="translationTooltipStyles";s.textContent=`
    .translate-word{display:inline-block;border-bottom:2px dotted #7b61ff;cursor:pointer;padding:0 2px;border-radius:5px}
    .translate-word.phrase-translate{font-size:1.04em;border-bottom:3px solid #7b61ff;background:rgba(123,97,255,.08)}
    .translate-word:hover,.translate-word:focus,.translate-word.translation-open{background:#fff1a8;border-bottom-style:solid;outline:none}
    #translationTip{position:fixed;z-index:2147483647;display:none;max-width:min(300px,82vw);padding:9px 13px;border-radius:12px;background:#29243d;color:#fff;font-size:15px;font-weight:600;line-height:1.3;box-shadow:0 6px 22px rgba(0,0,0,.25);pointer-events:none}
    #translationTip.show{display:block}
  `;document.head.appendChild(s)}

  function show(el){const tip=document.getElementById("translationTip");if(!el||!tip)return;tip.textContent="🇷🇺 "+el.dataset.translation;tip.classList.add("show");const r=el.getBoundingClientRect();const w=tip.offsetWidth;const h=tip.offsetHeight;let left=r.left+r.width/2-w/2;let top=r.top-h-10;if(top<8)top=r.bottom+10;tip.style.left=Math.max(8,Math.min(window.innerWidth-w-8,left))+"px";tip.style.top=Math.max(8,Math.min(window.innerHeight-h-8,top))+"px"}
  function hide(){document.getElementById("translationTip")?.classList.remove("show");document.querySelectorAll(".translate-word.translation-open").forEach(x=>x.classList.remove("translation-open"))}

  function scan(){const root=document.getElementById("lessonContent");if(!root)return;
    // First translate complete teaching phrases so the child sees the meaning of the whole sentence.
    const phraseWalker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!n.nodeValue.trim()||!p||p.closest(".translate-word,.feedback,script,style,button,input,textarea")||!/[A-Za-z]/.test(n.nodeValue))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});
    const phraseNodes=[];let pn;while((pn=phraseWalker.nextNode()))phraseNodes.push(pn);
    phraseNodes.forEach(node=>{const raw=node.nodeValue.trim(), key=raw.toLowerCase();if(!phraseDictionary[key])return;const span=document.createElement("span");span.className="translate-word phrase-translate";span.tabIndex=0;span.dataset.translation=phraseDictionary[key];span.setAttribute("role","button");span.setAttribute("aria-label",raw+" — "+phraseDictionary[key]);span.title="Наведите для перевода всей фразы";span.textContent=raw;node.parentNode.replaceChild(span,node)});
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!n.nodeValue.trim()||!p||p.closest(".translate-word,.feedback,script,style,button,input,textarea")||!/[A-Za-z]/.test(n.nodeValue))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const nodes=[];let n;while((n=walker.nextNode()))nodes.push(n);const re=/[A-Za-z]+(?:[’'][A-Za-z]+)?/g;nodes.forEach(node=>{if(!node.parentNode)return;const text=node.nodeValue;let m,last=0,changed=false;re.lastIndex=0;const frag=document.createDocumentFragment();while((m=re.exec(text))){const word=m[0],tr=dictionary[word.toLowerCase()];if(!tr)continue;changed=true;if(m.index>last)frag.appendChild(document.createTextNode(text.slice(last,m.index)));const span=document.createElement("span");span.className="translate-word";span.tabIndex=0;span.dataset.translation=tr;span.setAttribute("role","button");span.setAttribute("aria-label",word+" — "+tr);span.title="Нажми для перевода";span.textContent=word;frag.appendChild(span);last=m.index+word.length}if(changed){if(last<text.length)frag.appendChild(document.createTextNode(text.slice(last)));node.parentNode.replaceChild(frag,node)}})}

  function install(){styles();if(!document.getElementById("translationTip")){const tip=document.createElement("div");tip.id="translationTip";document.body.appendChild(tip)}
    document.addEventListener("mouseover",e=>{const el=e.target.closest?.(".translate-word");if(el)show(el)});
    document.addEventListener("focusin",e=>{const el=e.target.closest?.(".translate-word");if(el)show(el)});
    document.addEventListener("click",e=>{const el=e.target.closest?.(".translate-word");if(el){e.preventDefault();e.stopPropagation();document.querySelectorAll(".translation-open").forEach(x=>x.classList.remove("translation-open"));el.classList.add("translation-open");show(el)}else if(!e.target.closest("#translationTip"))hide()},true);
    document.addEventListener("keydown",e=>{if(e.key==="Escape")hide();if((e.key==="Enter"||e.key===" ")&&document.activeElement?.classList.contains("translate-word")){e.preventDefault();show(document.activeElement)}});
    window.addEventListener("scroll",()=>{const el=document.querySelector(".translate-word.translation-open");if(el)show(el)},true);
    window.addEventListener("resize",()=>{const el=document.querySelector(".translate-word.translation-open");if(el)show(el)});
    const root=document.getElementById("lessonContent");if(root)new MutationObserver(()=>{clearTimeout(window.__translationTimer);window.__translationTimer=setTimeout(scan,50)}).observe(root,{childList:true,subtree:true,characterData:true});
    scan();[200,700,1500,3000].forEach(t=>setTimeout(scan,t));
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();
